// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package auditdb

import (
	"context"
	"time"

	"github.com/comalonwizme/neurodent/backend/internal/shared/id"
)

const insertEvent = `-- name: InsertEvent :exec

INSERT INTO audit.events (
    id, occurred_at, tenant_id, actor_kind, actor_id,
    action, resource_type, resource_id, outcome, request_id
) VALUES (
    $1, $2,
    platform.current_tenant_id(), platform.current_actor_kind(), platform.current_actor_id(),
    $3, $4, $5, $6, $7
)
`

type InsertEventParams struct {
	ID           id.ID
	OccurredAt   time.Time
	Action       string
	ResourceType string
	ResourceID   *id.ID
	Outcome      string
	RequestID    *string
}

// Клиника и субъект события не передаются из Go: их подставляет БД из
// параметров транзакции (ADR-0014). Событие не может разойтись со scope,
// под которым выполнено действие.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.OccurredAt,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Outcome,
		arg.RequestID,
	)
	return err
}
