// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auditdb

import (
	"time"

	"github.com/comalonwizme/neurodent/backend/internal/shared/id"
)

// class=audit; Audit events (ADR-0014): ids and codes only, no PHI, no free text.
type AuditEvent struct {
	ID           id.ID
	OccurredAt   time.Time
	RecordedAt   time.Time
	TenantID     *id.ID
	ActorKind    string
	ActorID      *id.ID
	Action       string
	ResourceType string
	ResourceID   *id.ID
	Outcome      string
	RequestID    *string
}

// class=tenant; TECHNICAL: RLS probe of the tenant class for platform integration tests. Not business data.
type PlatformRlsProbe struct {
	ID       id.ID
	TenantID id.ID
	Note     string
}

// class=patient-registry; TECHNICAL: RLS probe of guardianship links. Not business data.
type PlatformRlsProbeGuardian struct {
	TenantID       id.ID
	GuardianUserID id.ID
	WardPatientID  id.ID
}

// class=patient-registry; TECHNICAL: RLS probe of patient cards. Not business data.
type PlatformRlsProbePatient struct {
	ID       id.ID
	TenantID id.ID
	UserID   *id.ID
	Note     string
}

// class=tenant-public; TECHNICAL: RLS probe of the tenant-public class. Not business data.
type PlatformRlsProbePublic struct {
	ID       id.ID
	TenantID id.ID
	Note     string
}

// class=patient-owned; TECHNICAL: RLS probe of the patient-owned class. Not business data.
type PlatformRlsProbeRecord struct {
	ID        id.ID
	TenantID  id.ID
	PatientID id.ID
	Note      string
}
