// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package probedb

import (
	"github.com/comalonwizme/neurodent/backend/internal/shared/id"
	"github.com/jackc/pgx/v5/pgtype"
)

// class=tenant; TECHNICAL: RLS probe of the tenant class for platform integration tests. Not business data.
type PlatformRlsProbe struct {
	ID       id.ID
	TenantID id.ID
	Note     string
}

// class=patient-registry; TECHNICAL: RLS probe of guardianship links. Not business data.
type PlatformRlsProbeGuardian struct {
	TenantID       id.ID
	GuardianUserID id.ID
	WardPatientID  id.ID
}

// class=patient-registry; TECHNICAL: RLS probe of patient cards. Not business data.
type PlatformRlsProbePatient struct {
	ID       id.ID
	TenantID id.ID
	UserID   pgtype.UUID
	Note     string
}

// class=tenant-public; TECHNICAL: RLS probe of the tenant-public class. Not business data.
type PlatformRlsProbePublic struct {
	ID       id.ID
	TenantID id.ID
	Note     string
}

// class=patient-owned; TECHNICAL: RLS probe of the patient-owned class. Not business data.
type PlatformRlsProbeRecord struct {
	ID        id.ID
	TenantID  id.ID
	PatientID id.ID
	Note      string
}
