// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: probe.sql

package probedb

import (
	"context"

	"github.com/comalonwizme/neurodent/backend/internal/shared/id"
)

const getProbe = `-- name: GetProbe :one
SELECT id, tenant_id, note FROM platform.rls_probe WHERE id = $1
`

func (q *Queries) GetProbe(ctx context.Context, argID id.ID) (PlatformRlsProbe, error) {
	row := q.db.QueryRow(ctx, getProbe, argID)
	var i PlatformRlsProbe
	err := row.Scan(&i.ID, &i.TenantID, &i.Note)
	return i, err
}

const insertProbe = `-- name: InsertProbe :exec

INSERT INTO platform.rls_probe (id, tenant_id, note) VALUES ($1, $2, $3)
`

type InsertProbeParams struct {
	ID       id.ID
	TenantID id.ID
	Note     string
}

// Запросы к технической таблице platform.rls_probe для integration-тестов.
func (q *Queries) InsertProbe(ctx context.Context, arg InsertProbeParams) error {
	_, err := q.db.Exec(ctx, insertProbe, arg.ID, arg.TenantID, arg.Note)
	return err
}

const listProbeNotes = `-- name: ListProbeNotes :many
SELECT note FROM platform.rls_probe ORDER BY note
`

func (q *Queries) ListProbeNotes(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listProbeNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var note string
		if err := rows.Scan(&note); err != nil {
			return nil, err
		}
		items = append(items, note)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
