// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: counters.sql

package ratelimitdb

import (
	"context"
	"time"
)

const deleteExpired = `-- name: DeleteExpired :execrows
DELETE FROM platform.rate_limit_counters
WHERE (key, window_start) IN (
    SELECT c.key, c.window_start FROM platform.rate_limit_counters c
    WHERE c.expires_at < $1
    LIMIT $2
)
`

type DeleteExpiredParams struct {
	Now       time.Time
	BatchSize int32
}

func (q *Queries) DeleteExpired(ctx context.Context, arg DeleteExpiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpired, arg.Now, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hit = `-- name: Hit :one

INSERT INTO platform.rate_limit_counters (key, window_start, hits, expires_at)
VALUES ($1, $2, 1, $3)
ON CONFLICT (key, window_start) DO UPDATE SET hits = platform.rate_limit_counters.hits + 1
RETURNING hits
`

type HitParams struct {
	Key         []byte
	WindowStart time.Time
	ExpiresAt   time.Time
}

// Один INSERT … ON CONFLICT атомарен при любой конкуренции: блокировку
// строки берёт Postgres, и два запроса не прочитают одно значение.
func (q *Queries) Hit(ctx context.Context, arg HitParams) (int32, error) {
	row := q.db.QueryRow(ctx, hit, arg.Key, arg.WindowStart, arg.ExpiresAt)
	var hits int32
	err := row.Scan(&hits)
	return hits, err
}
