// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ratelimitdb

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// class=audit; Audit events (ADR-0014): ids and codes only, no PHI, no free text.
type AuditEvent struct {
	ID           pgtype.UUID
	OccurredAt   time.Time
	RecordedAt   time.Time
	TenantID     pgtype.UUID
	ActorKind    string
	ActorID      pgtype.UUID
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	Outcome      string
	RequestID    pgtype.Text
}

// class=cell-global; Rate limit counters (ADR-0016): HMAC keys only, no personal data.
type PlatformRateLimitCounter struct {
	Key         []byte
	WindowStart time.Time
	Hits        int32
	ExpiresAt   time.Time
}

// class=tenant; TECHNICAL: RLS probe of the tenant class for platform integration tests. Not business data.
type PlatformRlsProbe struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
	Note     string
}

// class=patient-registry; TECHNICAL: RLS probe of guardianship links. Not business data.
type PlatformRlsProbeGuardian struct {
	TenantID       pgtype.UUID
	GuardianUserID pgtype.UUID
	WardPatientID  pgtype.UUID
}

// class=patient-registry; TECHNICAL: RLS probe of patient cards. Not business data.
type PlatformRlsProbePatient struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
	UserID   pgtype.UUID
	Note     string
}

// class=tenant-public; TECHNICAL: RLS probe of the tenant-public class. Not business data.
type PlatformRlsProbePublic struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
	Note     string
}

// class=patient-owned; TECHNICAL: RLS probe of the patient-owned class. Not business data.
type PlatformRlsProbeRecord struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	PatientID pgtype.UUID
	Note      string
}
